require "user.options"
require "user.keymaps"
require "user.lazy"
require "user.plugins"
-- require "user.cmp"
-- require "user.lsp"
-- require "user.telescope"
-- require "user.treesitter"
-- require "user.autopair"
-- require "user.comment"
-- require "user.git"
-- require "user.nvim-tree"
-- require "user.buffer"
-- require "user.runner"

